server:
  port: 4180

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.cloud.gateway: DEBUG

spring:
  # config:
  #   import: optional:file:.env[.properties]
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      mvc:
        routes:
          - id: hapi-fhir
            uri: ${hapi_fhir_uri:https://httpbin.org/}
            predicates:
              - Path=/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/actuator-api.html
# https://cloud.spring.io/spring-cloud-gateway/multi/multi__tls_ssl.html

# https://medium.com/att-israel/spring-cloud-gateway-mvc-migration-from-reactive-one-ed2025efc165

# https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.files.property-placeholders
