FROM percona/percona-distribution-postgresql:17.5

# FROM postgres:17.5-alpine

# https://hub.docker.com/_/postgres
# 70 is the standard uid/gid for "postgres" in Alpine as per the postgres:17.2-alpine Docker file:
# https://github.com/docker-library/postgres/blob/b23470265cc9c4bc283a88bf6c5054e3fca87c16/17/alpine3.21/Dockerfile
