apisix:
  node_listen: 9080
  enable_admin: false
  enable_ipv6: false

  ssl:
    enable: true
    listen_port: 9443
    ssl_protocols: "TLSv1.2 TLSv1.3"
    ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
    fallback_sni: "provider-directory.au.localhost"

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

# https://apisix.apache.org/docs/apisix/FAQ/